---
language: minimal
sudo: required
services: docker
before_install: sudo chmod -R 777 "$(pwd)"
install: ./ci/docker/docker_pull.sh

jobs:
  include:
    - name: "Lint all"
      env: SCRIPT="./ci/checks/all.sh"
    - name: "Gcc"
      env: SCRIPT="./ci/builders/gcc/build.sh"
    - name: "Clang"
      env: SCRIPT="./ci/builders/clang/build.sh"

script: ./ci/docker/docker_run.sh ${SCRIPT}
