language: cpp
sudo: required

services:
  - docker

jobs:
  include:
    - stage: "Checks"
      name: "Environment"
      env: SCRIPT="./ci/checks/environment.sh"
    - stage: "Checks"
      name: "Git symbols"
      env: SCRIPT="./ci/checks/git_symbols.sh"
    - stage: "Checks"
      name: "Spelling"
      env: SCRIPT="./ci/checks/spelling.sh"
    - stage: "Build"
      name: "Gcc"
      env: SCRIPT="./ci/builders/gcc/build.sh"
    - stage: "Build"
      name: "Clang"
      env: SCRIPT="./ci/builders/clang/build.sh"

before_install:
  - sudo chmod -R 777 "$(pwd)"

install:
  - ./ci/docker/docker_pull.sh

script:
  - ./ci/docker/docker_run.sh ${SCRIPT}