---
language: cpp
sudo: required

services:
  - docker

jobs:
  include:
    - name: "All"
      env: SCRIPT="./ci/checks/all.sh"
    - name: "Gcc"
      install: echo "nothing to install"
      script: ./ci/builders/gcc/build.sh
    - name: "Clang"
      install: echo "nothing to install"
      script: ./ci/builders/clang/build.sh

before_install:
  - sudo chmod -R 777 "$(pwd)"

install:
  - ./ci/docker/docker_pull.sh

script:
  - ./ci/docker/docker_run.sh ${SCRIPT}
