language: cpp
sudo: required

services:
  - docker

jobs:
  include:
    - stage: "Checks"
      name: "Git symbols"
      env: SCRIPT="./ci/checks/git_symbols.sh"
    - stage: "Checks"
      name: "Conventional git style"
      env: SCRIPT="./ci/checks/conventional_git_style.sh"
    - stage: "Checks"
      name: "Spelling"
      env: SCRIPT="./ci/checks/spelling.sh"
    - stage: "Checks"
      name: "Directories and files naming"
      env: SCRIPT="./ci/checks/directories_and_files_naming.sh"
    - stage: "Checks"
      name: "Md files style"
      env: SCRIPT="./ci/checks/md_files_style.sh"
    - stage: "Build"
      name: "Gcc"
      env: SCRIPT="./ci/builders/gcc/build.sh"
    - stage: "Build"
      name: "Clang"
      env: SCRIPT="./ci/builders/clang/build.sh"

before_install:
  - sudo chmod -R 777 "$(pwd)"

install:
  - ./ci/docker/docker_pull.sh

script:
  - ./ci/docker/docker_run.sh ${SCRIPT}