language: cpp
sudo: required

services:
  - docker

env:
- SCRIPT="./ci/tests/test_environment.sh"
- SCRIPT="./ci/builders/gcc/build.sh"
- SCRIPT="./ci/builders/clang/build.sh"

before_install:
  - sudo chmod -R 777 "$(pwd)"

install:
  - ./ci/docker/docker_pull.sh

script:
  - ./ci/docker/docker_run.sh ${SCRIPT}